### ISSUE TITLE
Kako združiti dve tabeli brez da se vrstice multiplicirajo?

### ISSUE THREAD

**Issue by klaratravnik** [klaratravnik/APPR-2021-22#1]
Pozdravljeni,
prosila bi za pomoč pri uvozu oz. že nadaljni analizi mojega projekta, in sicer, ko združujem dve tabeli, v mojem primeru tabeli "zemljisca" in "zivina3", kako jih združiti, da se podatki ne multiplicirajo in ne dobim iz cca 600 vrstic 3000? Združevala bi jih po stolpcu "regija" in "leto"? 
Prilagam link, kjer bi lahko bila rešitev: https://stackoverflow.com/questions/31707132/merge-without-row-multiplication-in-r.
Najlepša hvala že vnaprej!

**Comment by M4rble** [comment]
Zdravo,
ni mi čisto jasno kaj točno je problem, oziroma kaj bi želela narediti? Kolikor sem uspel pregledat tvoj projekt, se mi zdi da tako `left_join` kot `merge` ustrezno združita tabeli `zemljisca` in `zivina3`. Poiščeta vsa ujemanja iz stolpcev `regija` in `leto`, za ostale stolpce pa naredita vse možne kombinacije. Zaradi tega bo končna tabela logično precej daljša, s čemer pa ni nič narobe. Razen, če si morda opazila, da imaš kje (oziroma na večih mestih) 2 popolnoma enaki vrstici (ki se ne razlikujeta v nobeni spremenljivki), česar pa nisem zasledil. Drugače se mi zdita tabeli `test` in `test2` v ustrezni obliki za nadaljnjo obdelavo in analizo.
Sporoči, če sem morda narobe razumel, kaj bi si sploh želela narediti oziroma kaj te moti. Drugače bo pa še @katarinabrilej pogledala in pokomentirala, ko bo uspela.
Lp

**Comment by katarinabrilej** [comment]
Združevanje, ki ga želiš opraviti je smiselno za primer, ko bi imela v tabeli `zemljisca` za vsako leto in regijo sešteto skupno površino zemljišč, podobno za tabelo `zivina3` (za vsako leto in regijo skupno število vseh živali).
V takem primeru bi potem združena tabela predstavljala podatke o skupni površini zemljišč in skupnem številu živali glede na leto in regijo.

Če pa imaš v vsaki tabeli podatke še razdeljene na vrsto živine/vrsto zemljišča, potem lahko iz združene tabele (tabela `test`) dobiš podatke, ki jih v resnici nimaš - npr. koliko ovc je v gozdovih leta 2007 v regiji ce - če podrobno pogledaš je ta podatek enak kot število ovc na nerodovitnem zemljišču leta 2007 v regiji ce. To je smiselno, saj v posameznih tabelah teh podatkov ni, nastali so le zaradi združevanja.
